version: '3.8'

services:

  db:
    image: postgres
    restart: always
    environment:
      POSTGRES_DB: "dstream"
      POSTGRES_USER: "dstreamUser"
      POSTGRES_PASSWORD: "postgresspassword"
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  adminer:
    image: adminer
    restart: always
    ports:
      - 8080:8080

volumes:
  postgres-data: null